import { z } from 'zod';

// Schema for the structured output expected from the AI
export const AIGeneratedFrameSchema = z.object({
  mainImage: z.string().describe("Detailed English prompt for the main image generation AI."),
  backgroundImage: z.string().describe("Detailed English prompt for the background image generation AI."),
  bgm: z.string().describe("Detailed English prompt or description for background music suggestion."),
  narration: z.string().describe("The narration text for this frame in Brazilian Portuguese. 50 to 200 words"),
});

export type AIGeneratedFrame = z.infer<typeof AIGeneratedFrameSchema>;

// Schema representing the data stored in the database
export const StoryboardFrameDbSchema = z.object({
  id: z.string().uuid(),
  title: z.string().nullable().optional(), // Keep title optional in DB for now

  // Store the AI-generated prompts and narration
  mainImagePrompt: z.string(), // Store the prompt generated by the AI
  backgroundImagePrompt: z.string(), // Store the prompt generated by the AI
  bgmPrompt: z.string(), // Store the prompt generated by the AI
  narration: z.string(), // Store the narration generated by the AI

  // Placeholder for actual generated image/bgm URLs (to be added later if needed)
  mainImageUrl: z.string().nullable().optional(),
  backgroundImageUrl: z.string().nullable().optional(),
  bgmUrl: z.string().nullable().optional(),
  narrationAudioUrl: z.string().nullable().optional(), // Added for TTS output URL


  createdAt: z.date(),
});

// TypeScript type inferred from the DB schema
export type StoryboardFrameDb = z.infer<typeof StoryboardFrameDbSchema>;

// Example Usage (for reference)
// const aiOutput: AIGeneratedFrame = {
//   mainImage: 'Close up shot of a knight drawing his sword, dramatic lighting, fantasy art style',
//   backgroundImage: 'A dark and stormy castle background',
//   bgm: 'Tense orchestral music building up',
//   narration: 'The knight prepared for the final confrontation.',
// };

// const dbRecord: StoryboardFrameDb = {
//    id: '...',
//    mainImagePrompt: aiOutput.mainImage,
//    backgroundImagePrompt: aiOutput.backgroundImage,
//    bgmPrompt: aiOutput.bgm,
//    narration: aiOutput.narration,
//    createdAt: new Date(),
// }
