import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

export const storyboardFrames = sqliteTable('storyboard_frames', {
  // Using text for UUID, will be generated by application logic (e.g., crypto.randomUUID())
  id: text('id').primaryKey(),
  title: text('title'), // Nullable by default

  // Store the AI-generated prompts and narration
  mainImagePrompt: text('main_image_prompt').notNull(), // Renamed from mainImage
  backgroundImagePrompt: text('background_image_prompt').notNull(), // Renamed from backgroundImage
  bgmPrompt: text('bgm_prompt').notNull(), // Renamed from bgm
  narration: text('narration').notNull(), // Keep as is

  // Placeholder for actual generated image/bgm URLs (to be added later if needed)
  mainImageUrl: text('main_image_url'), // Added, nullable
  backgroundImageUrl: text('background_image_url'), // Added, nullable
  bgmUrl: text('bgm_url'), // Added, nullable
  narrationAudioUrl: text('narration_audio_url'), // Added, nullable

  // Store timestamp as integer (Unix epoch milliseconds)
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .notNull()
    .default(sql`(unixepoch('subsec') * 1000)`), // Use SQLite function for default timestamp
});

// Note: The previous optional prompt columns (mainImagePrompt, etc.) are effectively
// replaced by the renamed columns above which now store the AI's output prompts.
// The narrationPrompt column is removed as the input prompt isn't stored.
